name: Bug Report
description: Create a report to help us improve
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report

        Which version of the demo you are using? (please provide either a specific
        [commit hash](https://github.com/open-telemetry/opentelemetry-demo/commits/main)
        or a specific
        [release](https://github.com/open-telemetry/opentelemetry-demo/releases)).

  - type: textarea
    id: version
    attributes:
      label: Version
      description: Please provide the version of the demo you are using
      placeholder: "e.g., v1.2.3 or commit hash"
    validations:
      required: true

  - type: textarea
    id: symptom
    attributes:
      label: Symptom
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What do you expect to see?
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please describe the actual behavior experienced.
      placeholder: "Describe the actual behavior..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce
      description: |
        Could you provide the minimum required steps to resolve the issue you're seeing?
        
        We will close this issue if:
        * The steps you provided are complex.
        * If we can not reproduce the behavior you're reporting.
      placeholder: "Steps to reproduce..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please feel free to add any other context about the problem here.
      placeholder: "Any additional context..."

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0