name: Feature Request
description: Suggest an idea for this project
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request

        Before opening a feature request against this repo, consider whether the feature
        should/could be implemented in the [other OpenTelemetry client
        libraries](https://github.com/open-telemetry/). If so, please [open an issue on
        opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification/issues/new)
        first.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: If so, provide a concise description of the problem.
      placeholder: "Describe the problem..."

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to happen instead? What is the expected behavior?
      placeholder: "Describe your solution..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Which alternative solutions or features have you considered?
      placeholder: "Describe alternatives..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Feel free to add any other context about the feature request here.
      placeholder: "Any additional context..."

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0