# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  build_images:
    if: github.repository == 'open-telemetry/opentelemetry-demo'
    permissions: # required by the reusable workflow
      contents: read
      packages: write
    uses: ./.github/workflows/component-build-images.yml
